import type { Metadata } from "next"
import "./globals.css"
import StoreProvider from "./StoreProvider"
import { fontVariables } from "./fonts";

export const metadata: Metadata = {
  title: "Collaborative Canvas",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontVariables} antialiased`}
      >
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
